services:
  - type: web
    name: resume-parser-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: gunicorn backend:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.13"
